#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

cat /etc/s6-overlay/s6-rc.d/init-adduser/branding

echo '
To support DUBLOK, visit:
https://www.dublok.com/

───────────────────────────────────────
GID/UID
───────────────────────────────────────'
echo "
User UID:    $(id -u abc)
User GID:    $(id -g abc)
───────────────────────────────────────"
if [[ -f /build_version ]]; then
    cat /build_version
    echo '
───────────────────────────────────────
    '
fi


dockforgeown abc:abc /app
dockforgeown abc:abc /config
dockforgeown abc:abc /defaults
