name: Load and Run Composite Action

on: [push, pull_request]

jobs:
  load-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global url."https://${{ secrets.TOKEN }}@github.com".insteadOf "https://github.com"
        env:
          PRIVATE_REPO_TOKEN: ${{ secrets.TOKEN }}

      - name: Clone Private Configs
        run: git clone https://github.com/DublokSoftware/workflows.git private-configs
        env:
          PRIVATE_REPO_TOKEN: ${{ secrets.TOKEN }}

      - name: Use Composite Action
        uses: ./private-configs/.github/actions/${{ github.event.repository.name }}-action
