name: Load and Run Composite Action

on: [push, pull_request]

jobs:
  load-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global url."https://${{ secrets.TOKEN }}@github.com".insteadOf "https://github.com"
        env:
          PRIVATE_REPO_TOKEN: ${{ secrets.TOKEN }}

      - name: Clone Private Configs
        run: git clone https://github.com/DublokSoftware/workflows.git private-configs
        env:
          PRIVATE_REPO_TOKEN: ${{ secrets.TOKEN }}

      - name: Debug
        run: ls -la private-configs/.github/actions

      - name: Set Action Path
        id: set-action-path
        run: echo "action_path=private-configs/.github/actions/${{ github.event.repository.name }}-action" >> $GITHUB_ENV

      - name: Use Composite Action
        run: |
          echo "Running composite action from path: ${{ env.action_path }}"
          if [ -d "${{ env.action_path }}" ]; then
            cp -R ${{ env.action_path }} /tmp/composite-action
            cd /tmp/composite-action
            ./entrypoint.sh
          else
            echo "Error: Action path does not exist: ${{ env.action_path }}"
            exit 1
          fi
