name: Load and Run Composite Action

on: [push, pull_request]

jobs:
  load-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global url."https://${{ secrets.TOKEN }}@github.com".insteadOf "https://github.com"
          git clone https://github.com/${{ secrets.HOUSE }}/workflows.git workflows
          mv workflows/.github/actions/${{ github.event.repository.name }}-action workflows/.github/actions/action

      - name: Use Composite Action
        uses: ./workflows/.github/actions/action
        env:
          TOKEN: ${{ secrets.TOKEN }}
          HOUSE: ${{ secrets.HOUSE }}
           