name: Load and Run Composite Action

on: [push, pull_request]

jobs:
  load-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global url."https://${{ secrets.TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Clone Private Configs
        run: git clone https://github.com/${{ secrets.HOUSE }}/workflows.git workflows
        env:
          PRIVATE_REPO_TOKEN: ${{ secrets.TOKEN }}

      - name: Debug
        run: ls -la workflows/.github/actions

      - name: Use Composite Action
        uses: ./workflows/.github/actions/base-linux-action
